import warnings

def add(fragment1, fragment2, width):...
def adpcm2lin(adpcmfragment, width, state):...
def alaw2lin(fragment, width):...
def avg(fragment, width):...
def avgpp(fragment, width):...
def bias(fragment, bias, width):...
def byteswap(fragment, width):...
def cross(fragment, width):...
def findfactor(fragment, reference):...
def findit(fragment, reference):...
def findmax(fragment, length):...
def getsample(fragment, width, index):...
def lin2adpcm(fragment, width, state):...
def lin2alaw(fragment, width):...
def lin2lin(fragment, width, new_width):...
def lin2ulaw(fragment, width):...
def max(fragment, width):...
def maxpp(fragment, width):...
def minmax(fragment, width):...
def ratecv(fragment, width, nchannels, inrate, outrate, state, weightA=1, weightB=0):...
def reverse(fragment, width):...
def rms(fragment, width):...
def to_mono(fragment, width, lfactor, rfactor):...
def to_stereo(fragment, width, lfactor, rfactor):...
def ulaw2lin(fragment, width):...


def tomono(fragment, width, lfactor, rfactor): 
    warnings.warn("This function is deprecated. Use to_mono", DeprecationWarning, stacklevel=2)
    return to_mono(fragment, width, lfactor, rfactor)

def tostereo(fragment, width, lfactor, rfactor): 
    warnings.warn("This function is deprecated. Use to_stereo", DeprecationWarning, stacklevel=2)
    return to_stereo(fragment, width, lfactor, rfactor)
